export const BILLING_STATUS_ISSUE = 'ISSUE';
export const BILLING_STATUS_RECEIVING = 'RECEIVING';
export const BILLING_STATUS_PAID = 'PAID';
export const BILLING_STATUS_CLOSED = 'CLOSED';
export const BILLING_STATUSES = [
    BILLING_STATUS_ISSUE,
    BILLING_STATUS_RECEIVING,
    BILLING_STATUS_PAID,
    BILLING_STATUS_CLOSED
];

export const BILLING_PERIOD_RECENT_MONTHS = 'Recent 12 months';
export const BILLING_PERIOD_MONTHS_AGO = '12 months ago';
export const BILLING_PERIODS = [
    BILLING_PERIOD_RECENT_MONTHS,
    BILLING_PERIOD_MONTHS_AGO
];